-- CREATE DATABASE LibraryManagement
-- USE LibraryManagement

-- CREATE TABLE Books (
	BookId INT IDENTITY(1,1) PRIMARY KEY,
	BookTitle VARCHAR(MAX) NOT NULL,
	AuthorName  VARCHAR(MAX) NOT NULL,
	Cost INT NOT NULL,
	AvailableQuantity INT NOT NULL
);

-- CREATE TABLE Roles (
	RoleId INT IDENTITY(1,1) PRIMARY KEY,
	RoleName VARCHAR(MAX) NOT NULL
);

-- CREATE TABLE Students (
	StudentId INT IDENTITY(1,1) PRIMARY KEY,
	StudentName VARCHAR(255) NOT NULL UNIQUE,
	USN VARCHAR(MAX) NOT NULL,
	RoleId INT NOT NULL,
	CONSTRAINT FK_RoleId FOREIGN KEY (RoleId) REFERENCES Roles(RoleId)
);

--	ALTER TABLE Students
--	ALTER COLUMN USN VARCHAR(50) NOT NULL UNIQUE ;
--	ALTER TABLE Students ADD CONSTRAINT Uk_usn UNIQUE(USN)
--	DROP TABLE Students

-- CREATE TABLE Orders (
	OrderId INT IDENTITY(1,1) PRIMARY KEY,
	BookId INT NOT NULL,
	StudentId  INT NOT NULL,
	OrderDate DATE NOT NULL,
	ReturnDate DATE NOT NULL,
	CONSTRAINT FK_BookId FOREIGN KEY (BookId) REFERENCES Books(BookId),
	CONSTRAINT FK_StudentId FOREIGN KEY (StudentId) REFERENCES Students(StudentId)
);

-- ALTER TABLE Orders
-- ALTER COLUMN ReturnDate DATE 

-- CREATE TABLE Login (
	LoginId INT IDENTITY(1,1) PRIMARY KEY,
	StudentId  INT NOT NULL UNIQUE,
	[Password] VARCHAR(MAX) NOT NULL,
	LoginStatus BIT NOT NULL,
	CONSTRAINT FK_StudentIdInRoles FOREIGN KEY (StudentId) REFERENCES Students(StudentId)
);


